apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath
provisioner: hostpath.csi.goblin.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
#volumeBindingMode: Immediate