apiVersion: v1
kind: ServiceAccount
metadata:
  name: goblin-csi-driver
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: goblin-csi-driver
subjects:
  - kind: ServiceAccount
    name: goblin-csi-driver
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io